### ISSUE TITLE
貸出機だとファイルパスが長すぎる場合がある

### ISSUE THREAD

**Issue by umiwatarin** [KPC-U16/PortableEditor-Pub#16]
ふぁっきゅーうぃんどうず。

**Comment by noko1024** [comment]
具体的な発生状況をお願いします。

**Comment by umiwatarin** [comment]
![image](https://user-images.githubusercontent.com/9639926/140009922-b9f7f9f3-f763-4d66-95bb-e4f49ad3e5c8.png)

**Comment by noko1024** [comment]
.devcontainerのファイルパスと中身が確認したいです

**Comment by umiwatarin** [comment]
PortableEditor-Pub-1.0.1 以下の複数のディレクトリで確認されています

PortableEditor-Pub-1.0.1\Editor\vscode\data\extensions\ms-vscode-remote.remote-containers-0.202.5\dist\node_modules\vscode-dev-containers\containers\alpine\.devcontainer

![image](https://user-images.githubusercontent.com/9639926/140010300-4506ac9b-2bef-4948-842f-a693f51c3ea1.png)

**Comment by noko1024** [comment]
ファイル移動時のエラーですか？

**Comment by umiwatarin** [comment]
はい
DLからのバッチ処理時にどうなるかは今から検証します

**Comment by noko1024** [comment]
バッチ処理時は正常に動作すると思います。
LiveShareの拡張機能を格納しているファイルパスが深すぎることが起因しているものです。

**Comment by noko1024** [comment]
現在有効だと思われる解決策はLiveShareをアンインストールすることです。

**Comment by noko1024** [comment]
過去の利用状況等も勘案し、デフォルトで拡張機能の追加命令に含めないことも検討しています。

**Comment by noko1024** [comment]
とりあえず対応したのでClose
